# Generated by Django 2.2 on 2019-04-10 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('option', '0001_initial'),
        ('account', '0001_initial'),
        ('version', '0002_version_image'),
        ('couleur', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Prix_Minimal', models.FloatField()),
                ('Description', models.TextField(blank=True, null=True)),
                ('Couleur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='couleur.Couleur')),
                ('Id_Automobiliste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Automobiliste')),
                ('Options', models.ManyToManyField(related_name='Annonces', to='option.Option')),
                ('Version', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='version.Version')),
            ],
        ),
        migrations.CreateModel(
            name='AnnonceOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annonce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annonce.Annonce')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='option.Option')),
            ],
        ),
        migrations.CreateModel(
            name='Annonce_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Images_Annonce', models.ImageField(upload_to='Annonce/')),
                ('Annonce', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Images_Annonce', to='annonce.Annonce')),
            ],
        ),
    ]
