# Generated by Django 2.2 on 2019-09-15 21:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='date',
            field=models.DateField(blank=None, default=datetime.date.today),
        ),
    ]
