# Generated by Django 2.2 on 2019-04-09 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marque',
            fields=[
                ('Id_Marque', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Nom_Marque', models.CharField(max_length=100)),
                ('Logo', models.ImageField(blank=True, default='logo/default.png', upload_to='logo')),
            ],
        ),
    ]
