# Generated by Django 2.2 on 2019-04-09 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modele', '0001_initial'),
        ('option', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option_Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Default', models.BooleanField(default=False)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='option.Option')),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('Code_Version', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Nom_Version', models.CharField(max_length=200)),
                ('Id_Modele', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Version_set', to='modele.Modele')),
                ('option_Version', models.ManyToManyField(through='version.Option_Version', to='option.Option')),
            ],
        ),
        migrations.AddField(
            model_name='option_version',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='version.Version'),
        ),
    ]
