# Generated by Django 2.2 on 2019-06-26 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commande',
            new_name='reservations',
        ),
    ]
