# Generated by Django 2.2 on 2019-06-26 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_auto_20190626_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicule',
            name='Vendu',
            field=models.BooleanField(default=False),
        ),
    ]
